#include "harness.h"
#include "audio/SpFlanger.h"

#include <algorithm>
#include <cmath>
#include <cstring>
#include <vector>

using SH::SpFlanger;
using SH::SpFlangerParams;

// The deterministic test signal, identical (in double) to the generator in
// the sound session's reference script. Any change here must be mirrored
// there and the checkpoints regenerated.
static void TestInput(std::uint64_t n, float& l, float& r) {
    const double t = static_cast<double>(n) / 48000.0;
    constexpr double kTau = 6.28318530717958647692;
    l = static_cast<float>(0.4 * std::sin(kTau * 220.0 * t) +
                           0.2 * std::sin(kTau * 917.0 * t + 0.5));
    r = static_cast<float>(0.4 * std::sin(kTau * 220.0 * t + 0.3) +
                           0.2 * std::sin(kTau * 1333.0 * t));
}

// Fast test parameters: a full LFO cycle plus the whole engage ramp fit
// inside 8192 frames. The audible "classic" defaults share every code
// path; only the numbers differ.
static SpFlangerParams TestParams() {
    SpFlangerParams p;
    p.rateHz      = 8.0f;
    p.baseMs      = 0.4f;
    p.depthMs     = 3.6f;
    p.feedback    = 0.55f;
    p.wet         = 0.8f;
    p.stereoPhase = 0.25f;
    p.trimDb      = -2.5f;
    p.rampSec     = 0.010f;
    return p;
}

// Cross-implementation reference: generated by the independent float64
// Python implementation (the same algorithm family that rendered the
// audition previews the user approved). One checkpoint per 64 frames.
// Regenerate with the sound session's gen_flanger_reference.py if the
// DSP semantics ever change - agreement here is what "matches the
// approved preview sound" means.
static constexpr double kRefL[128] = {
    +0.561899675, -0.127931797, -0.284547755, +0.237658374,
    +0.165442928, -0.151681238, +0.047013222, -0.004329087,
    -0.089554211, +0.345135161, +0.319434229, -0.413852650,
    -0.370772262, +0.284170259, -0.027118740, -0.475339550,
    +0.137556000, +0.335615169, -0.345915126, -0.164713411,
    +0.385510822, -0.133819917, -0.324417909, +0.385467802,
    +0.103186882, -0.542922465, +0.153555307, +0.490262075,
    -0.354926229, -0.265498522, +0.379430599, -0.006995911,
    -0.199062858, +0.180734107, -0.042048288, -0.209016203,
    +0.222791766, +0.159570676, -0.322338954, -0.016180779,
    +0.160926498, +0.130160492, -0.151912621, -0.163045912,
    +0.093775507, +0.234655557, -0.121486537, -0.257530181,
    +0.308372722, -0.050828411, -0.059161037, +0.079931286,
    -0.040121752, -0.236328857, +0.221279053, +0.310246244,
    -0.495522192, -0.138530291, +0.547276321, -0.016753845,
    -0.499303941, +0.144277610, +0.396200301, -0.342414757,
    -0.143313750, +0.460783977, -0.209102426, -0.413862939,
    +0.524666317, +0.206300212, -0.676783582, +0.072862299,
    +0.626490437, -0.315482171, -0.426923733, +0.448222992,
    +0.176447071, -0.446822114, +0.026769070, +0.321621849,
    -0.108929042, -0.061333774, +0.104734821, -0.359968319,
    -0.392895084, +0.220081424, +0.171865132, -0.274752897,
    -0.040608238, +0.244819163, -0.048069322, -0.197257688,
    -0.070166945, -0.068522400, +0.149149850, +0.378060981,
    +0.067034938, -0.117432621, +0.253695721, +0.163612961,
    -0.373545150, -0.187758292, +0.291827820, +0.135361725,
    +0.037875509, +0.212276812, -0.163017422, -0.418401669,
    +0.149361857, +0.182623202, -0.481864488, -0.140040393,
    +0.504030764, -0.160245567, -0.548297352, +0.323875329,
    +0.325993180, -0.478673728, -0.050588828, +0.412711105,
    -0.290466513, -0.218036738, +0.479386484, -0.072799811,
    -0.471825621, +0.262581323, +0.323157799, -0.254702964,
};
static constexpr double kRefR[128] = {
    +0.137007774, -0.300925751, +0.045624394, +0.474713101,
    -0.365866495, -0.369880354, +0.684464497, +0.212019452,
    -0.415770092, +0.021770161, -0.089538504, -0.300955286,
    -0.083246171, -0.034121021, -0.150457202, +0.033177798,
    +0.398632210, +0.136294831, -0.156947764, +0.016632982,
    +0.358762921, +0.004599493, -0.389054872, -0.194630125,
    +0.042736289, -0.152809587, -0.198744059, +0.053303919,
    +0.106776004, +0.053688299, +0.299491009, +0.272751962,
    -0.254116036, -0.065025120, +0.373884383, -0.123885541,
    -0.631412004, +0.140908897, +0.531122378, -0.240930035,
    -0.150943107, +0.440038397, -0.166387789, -0.385948441,
    +0.449965129, +0.145432081, -0.599939097, +0.164464212,
    +0.573746635, -0.406623656, -0.410895220, +0.492490741,
    +0.199942375, -0.398276569, -0.069042577, +0.228116168,
    +0.096684938, -0.306411842, +0.255598704, -0.065096384,
    -0.214874962, +0.259998297, +0.153826432, -0.454318721,
    +0.080467536, +0.323731254, -0.131900308, -0.151736919,
    +0.052819128, +0.026504504, +0.146354256, -0.087061360,
    +0.001149558, -0.260337433, +0.297375924, +0.182864658,
    -0.405387462, -0.063830063, +0.475310486, -0.245324163,
    -0.091991783, +0.104059020, -0.014269689, -0.219872694,
    +0.370871161, +0.026731789, -0.508825071, +0.206576508,
    +0.496861225, -0.356416137, -0.380859124, +0.436864796,
    +0.246411617, -0.477095334, -0.054370592, +0.435343423,
    -0.166375270, -0.204565230, +0.299756017, -0.184348665,
    -0.294254303, +0.539927801, +0.308929095, -0.471828895,
    -0.210625436, +0.165548795, -0.135812837, -0.337781196,
    +0.010051414, +0.243280155, +0.089149509, +0.156382668,
    +0.191366235, +0.089098923, +0.029649969, +0.104803950,
    +0.000753145, -0.402293306, -0.220316824, +0.201352843,
    +0.060087469, -0.411649006, -0.013337410, +0.387795658,
    +0.064169572, -0.196966028, +0.169533202, +0.132895184,
};

static void RunTests() {
    // 1) Cross-validation against the independent Python reference,
    //    processed in ragged chunks to prove chunk-size independence
    //    (the device callback slices arbitrarily).
    {
        SpFlanger fl;
        fl.Configure(TestParams());
        fl.SetActive(true);
        constexpr std::uint32_t kN = 8192;
        std::vector<float> buf(kN * 2);
        for (std::uint64_t n = 0; n < kN; ++n)
            TestInput(n, buf[n * 2], buf[n * 2 + 1]);
        const std::uint32_t chunks[] = { 480, 37, 1024, 1, 503, 6147 };
        std::uint32_t at = 0, ci = 0;
        while (at < kN) {
            const std::uint32_t want =
                std::min(chunks[ci++ % 6], kN - at);
            fl.Process(buf.data() + at * 2, want);
            at += want;
        }
        double worst = 0.0;
        for (int k = 0; k < 128; ++k) {
            const std::uint32_t f = 64 * k + 63;
            worst = std::max(worst,
                             std::abs(buf[f * 2] - kRefL[k]));
            worst = std::max(worst,
                             std::abs(buf[f * 2 + 1] - kRefR[k]));
        }
        // float32 state vs the float64 reference through a 0.55 feedback
        // loop: observed ~1e-6; 5e-4 still fails on any structural error.
        CHECK(worst < 5e-4);
    }

    // 2) Inactive filter is a bit-exact no-op - it must never touch the
    //    buffer at all.
    {
        SpFlanger fl;
        fl.Configure(TestParams());
        std::vector<float> buf(2048 * 2), ref(2048 * 2);
        for (std::uint64_t n = 0; n < 2048; ++n)
            TestInput(n, buf[n * 2], buf[n * 2 + 1]);
        ref = buf;
        fl.Process(buf.data(), 2048);
        CHECK(std::memcmp(buf.data(), ref.data(),
                          buf.size() * sizeof(float)) == 0);
    }

    // 3) Disengage settles back to the bit-exact no-op within the ramp,
    //    ready for a clean re-engage.
    {
        SpFlanger fl;
        fl.Configure(TestParams());
        fl.SetActive(true);
        std::vector<float> buf(4096 * 2);
        for (std::uint64_t n = 0; n < 4096; ++n)
            TestInput(n, buf[n * 2], buf[n * 2 + 1]);
        fl.Process(buf.data(), 4096);
        fl.SetActive(false);
        fl.Process(buf.data(), 4096);  // ramp is 480 samples; plenty
        CHECK(fl.Idle());
        std::vector<float> ref(1024 * 2);
        for (std::uint64_t n = 0; n < 1024; ++n)
            TestInput(n, ref[n * 2], ref[n * 2 + 1]);
        auto probe = ref;
        fl.Process(probe.data(), 1024);
        CHECK(std::memcmp(probe.data(), ref.data(),
                          ref.size() * sizeof(float)) == 0);
    }

    // 4) Stability guard: an absurd feedback request is clamped and five
    //    seconds of full-scale input stays bounded (comb peak with the
    //    clamped 0.74 loop tops out well under 4x).
    {
        SpFlangerParams p = TestParams();
        p.feedback        = 0.99f;  // Configure must clamp this
        p.wet             = 1.0f;
        SpFlanger fl;
        fl.Configure(p);
        fl.SetActive(true);
        std::vector<float> buf(4800 * 2);
        float              peak = 0.0f;
        for (int block = 0; block < 50; ++block) {
            for (std::uint64_t n = 0; n < 4800; ++n) {
                const std::uint64_t g = block * 4800 + n;
                // harsh broadband: full-scale square-ish drive
                const float v = ((g / 40) % 2) ? 1.0f : -1.0f;
                buf[n * 2] = buf[n * 2 + 1] = v;
            }
            fl.Process(buf.data(), 4800);
            for (float s : buf) peak = std::max(peak, std::abs(s));
        }
        CHECK(peak < 4.0f);
        CHECK(std::isfinite(peak));
    }

    // 5) The engage ramp actually ramps: early output is nearly dry,
    //    and by the end of the ramp the wet path is audibly present.
    {
        SpFlanger fl;
        SpFlangerParams p = TestParams();
        fl.Configure(p);
        fl.SetActive(true);
        constexpr std::uint32_t kN = 2048;  // ramp = 480 samples
        std::vector<float> buf(kN * 2), dry(kN * 2);
        for (std::uint64_t n = 0; n < kN; ++n) {
            TestInput(n, buf[n * 2], buf[n * 2 + 1]);
            dry[n * 2]     = buf[n * 2];
            dry[n * 2 + 1] = buf[n * 2 + 1];
        }
        fl.Process(buf.data(), kN);
        double early = 0.0, late = 0.0;
        for (std::uint32_t f = 0; f < 48; ++f)
            early = std::max(early,
                             static_cast<double>(std::abs(
                                 buf[f * 2] - dry[f * 2])));
        for (std::uint32_t f = 1024; f < kN; ++f)
            late = std::max(late, static_cast<double>(std::abs(
                                      buf[f * 2] - dry[f * 2])));
        CHECK(early < 0.15);   // first ms: wet is barely open
        CHECK(late > 0.05);    // settled: the effect is unmistakably there
        CHECK(late > early);
    }
}

TEST_MAIN("SpFlanger")
